name: multi_utility_app
description: "All-in-One Multi Utility & Creative Tools Suite with AdMob"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  pdf: ^3.10.8
  printing: ^5.13.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
